theme: jekyll-theme-minimal
title: Code 201 Reading Notes
description: This site is used to display my reading notes and assignments.
source: reading-notes/main

# Welcome to MrWolfShark's Reading Notes

## **Table of Contents**

1. Assignment 1
2. Assignment 2
3. Assignment 3
4. Assignment 4
5. Assignment 5
6. Assignment 6
7. Assignment 7
8. Assignment 8
9. Assignment 9
10. Assignment 10
11. Assignment 11
12. Assignment 12
13. Assignment 13
14. Assignment 14
15. Assignment 15

### **Assignment 1**
